services:
  # Backend service (server)
  backend:
    build:
      context: ./server  
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development  

  # Frontend service (client)
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development 
    depends_on:
      - backend 
